// src/App.tsx
import { useState } from 'react'
import { ClinicianTraining } from './screens/ClinicianTraining'
import { ColorfulSemanticsConfig } from './screens/ColorfulSemanticsConfig'
import { HomeworkAdded } from './screens/HomeworkAdded'
import { AoCGuidance } from './screens/AoCGuidance'
import { ChildIntro } from './screens/ChildIntro'
import { ExerciseScreen, type ExerciseId } from './screens/ExerciseScreen'
import { SessionComplete } from './screens/SessionComplete'
import { ParentSummary } from './screens/ParentSummary'
import { Summary } from './screens/Summary'
import type { SessionConfig, SessionResults, ExerciseResult } from './types/session'

type Screen =
  | 'training'
  | 'cs-config'
  | 'homework-added'
  | 'aoc-guidance'
  | 'child-intro'
  | 'exercise'
  | 'session-complete'
  | 'parent-summary'
  | 'summary'

interface ClinicConfig {
  typedAnswerEnabled: boolean
  supportLevel: SessionConfig['supportLevel']
  exerciseCount: number
  topics: string[]
  showResultsToChild: boolean
}

const DEFAULT_SESSION_CONFIG: SessionConfig = {
  launchContext: 'clinic',
  typedAnswerEnabled: true,
  supportLevel: 'standard',
  exerciseCount: 3,
  topics: ['Pirates', 'Everyday actions'],
  showResultsToChild: true,
}

export default function App() {
  const [screen, setScreen] = useState<Screen>('training')
  const [exerciseId, setExerciseId] = useState<ExerciseId>(1)
  const [sessionConfig, setSessionConfig] = useState<SessionConfig>(DEFAULT_SESSION_CONFIG)
  const [exerciseResults, setExerciseResults] = useState<(ExerciseResult | null)[]>([null, null, null])
  const [sessionStart, setSessionStart] = useState<Date>(new Date())

  const startSession = (config: SessionConfig) => {
    setSessionConfig(config)
    setExerciseId(1)
    setExerciseResults([null, null, null])
    setSessionStart(new Date())
    setScreen('child-intro')
  }

  const handleStartTraining = (cfg: ClinicConfig) => {
    startSession({ ...cfg, launchContext: 'clinic' })
  }

  const handleAddToHomework = (cfg: ClinicConfig) => {
    // Store config for when homework is launched, keep launchContext pending
    setSessionConfig({ ...cfg, launchContext: 'home' })
    setScreen('homework-added')
  }

  const handleStartFromHomework = () => {
    // Home launch → show AoC guidance first
    setExerciseId(1)
    setExerciseResults([null, null, null])
    setSessionStart(new Date())
    setScreen('aoc-guidance')
  }

  const handleExerciseComplete = (result: ExerciseResult) => {
    const idx = result.exerciseNumber - 1
    setExerciseResults(prev => {
      const next = [...prev]
      next[idx] = result
      return next
    })
    if (result.exerciseNumber < sessionConfig.exerciseCount) {
      setExerciseId((result.exerciseNumber + 1) as ExerciseId)
    } else {
      setScreen('session-complete')
    }
  }

  const getSessionResults = (): SessionResults => ({
    config: sessionConfig,
    exercises: exerciseResults,
    sessionStart,
    sessionEnd: new Date(),
  })

  switch (screen) {
    case 'training':
      return (
        <ClinicianTraining
          onOpenColorfulSemantics={() => setScreen('cs-config')}
        />
      )

    case 'cs-config':
      return (
        <ColorfulSemanticsConfig
          onAddToHomework={handleAddToHomework}
          onStartTraining={handleStartTraining}
          onBack={() => setScreen('training')}
        />
      )

    case 'homework-added':
      return (
        <HomeworkAdded
          onStartFromList={handleStartFromHomework}
          onBack={() => setScreen('cs-config')}
        />
      )

    case 'aoc-guidance':
      return (
        <AoCGuidance
          onStart={() => setScreen('child-intro')}
        />
      )

    case 'child-intro':
      return (
        <ChildIntro
          sessionConfig={sessionConfig}
          onStart={() => setScreen('exercise')}
        />
      )

    case 'exercise':
      return (
        <ExerciseScreen
          key={exerciseId}
          exerciseId={exerciseId}
          sessionConfig={sessionConfig}
          onComplete={handleExerciseComplete}
        />
      )

    case 'session-complete':
      return (
        <SessionComplete
          sessionResults={getSessionResults()}
          onShowParentSummary={() => setScreen('parent-summary')}
          onSeeSummary={() => setScreen('summary')}
          onFinish={() => setScreen('training')}
        />
      )

    case 'parent-summary':
      return (
        <ParentSummary
          sessionResults={getSessionResults()}
          onDone={() => setScreen('training')}
        />
      )

    case 'summary':
      return (
        <Summary
          sessionResults={getSessionResults()}
          onDone={() => setScreen('training')}
        />
      )
  }
}

// src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import ClinicianTraining from './screens/ClinicianTraining.vue'
import ColorfulSemanticsConfig from './screens/ColorfulSemanticsConfig.vue'
import ChildIntro from './screens/ChildIntro.vue'
import Exercise from './screens/Exercise.vue'
import SessionComplete from './screens/SessionComplete.vue'
import Summary from './screens/Summary.vue'
import type { ExerciseResult, SessionConfig, SessionResults } from './types/session'

type Screen = 'training' | 'config' | 'intro' | 'exercise' | 'complete' | 'summary'
const screen = ref<Screen>('training')
const exerciseNumber = ref<1 | 2 | 3>(1)
const sessionStart = ref(new Date())
const config = ref<SessionConfig>({ launchContext: 'clinic', typedAnswerEnabled: true, supportLevel: 'standard', exerciseCount: 3, topics: ['Pirates', 'Everyday actions'], showResultsToChild: true })
const exerciseResults = ref<(ExerciseResult | null)[]>([null, null, null])
const sessionResults = computed<SessionResults>(() => ({ config: config.value, exercises: exerciseResults.value, sessionStart: sessionStart.value, sessionEnd: new Date() }))

function start(configWithoutContext: Omit<SessionConfig, 'launchContext'>) {
  config.value = { ...configWithoutContext, launchContext: 'clinic' }
  exerciseNumber.value = 1; exerciseResults.value = [null, null, null]; sessionStart.value = new Date(); screen.value = 'intro'
}
function complete(result: ExerciseResult) {
  exerciseResults.value[result.exerciseNumber - 1] = result
  if (result.exerciseNumber < config.value.exerciseCount) {
    exerciseNumber.value = (result.exerciseNumber + 1) as 1 | 2 | 3
  } else screen.value = 'complete'
}
function reset() { screen.value = 'training' }
</script>

<template>
  <ClinicianTraining v-if="screen === 'training'" @open="screen = 'config'" />
  <ColorfulSemanticsConfig v-else-if="screen === 'config'" @start="start" @back="reset" />
  <ChildIntro v-else-if="screen === 'intro'" :config="config" @start="screen = 'exercise'" />
  <Exercise v-else-if="screen === 'exercise'" :exercise-number="exerciseNumber" :config="config" @complete="complete" />
  <SessionComplete v-else-if="screen === 'complete'" :results="sessionResults" @summary="screen = 'summary'" @finish="reset" />
  <Summary v-else :results="sessionResults" @done="reset" />
</template>
